// ASSIGNMENT NO 14 
var invitation = ["\n\n\"I WANNA INVITE YOU  OWAIS IN MY BROTHER WEDDING ANNIVERSARY\",\n\"I WOULD LIKE TO INVITE YOU YAZDAN IN MY BROTHER WEDDING ANNIVERSAR\",\n\"I WOULD YOU LIKE TO INVITE YOU ERIC  IN MY BROTHER WEDDING ANNIVERSARY \"\n\n"
];
console.log(invitation);
// ASSIGNMENT NO 15 
console.log("".concat(invitation, " BUT  OUR FRIEND ERIC CANT JOIN IT"));
console.log("NOW I'M INVITING MY NEW FRRIEND REPLACING ERIC");
var invitationFinal = [
    "I WANNA INVITE YOU  OWAIS IN MY BROTHER WEDDING ANNIVERSARY",
    "I WOULD LIKE TO INVITE YOU YAZDAN IN MY BROTHER WEDDING ANNIVERSAR",
    "I WOULD YOU LIKE TO INVITE YOU HENRY  IN MY BROTHER WEDDING ANNIVERSARY ON ERIC PLACE",
];
console.log(invitationFinal);
// CHAPTER NO 16
console.log("NOW I HAVE A GREAT DINNER TABLE SO THAT I WANNA INVITE THREE MORE GUESTS");
var bigTable = ["\n\n\"I WOULD YOU LIKE TO INVITE OWAIS ON MY BROTHER WEDDING ANNIVERSARY\",\n\"I would like to invite HASEEB ON MY BROTHER WEDDING ANNIVERSARY\",\n\"I WOULD LIKE TO INVITE ERIC ON MY BROTHER WEDDING AANNIVERARY\",\n\"I WOULD LIKE TO INVITE MY FOURTH FRIEND ON MY BROTHER WEDDING ANNIVERSARY\",\n\"I WOULD LIKE TO INVITE MY FIFTH FRIEND ON MY BROTHER WEDDING ANNIVERSARY\",\n\"I WOULD LIKE TO INVITE MY SIXTHH FRIEND ON MY BROTHER WEDDING ANNIVERSARY\"\n\n"];
