// ASSIGNMENT NO 14 


let invitation = [`

"I WANNA INVITE YOU  OWAIS IN MY BROTHER WEDDING ANNIVERSARY",
"I WOULD LIKE TO INVITE YOU YAZDAN IN MY BROTHER WEDDING ANNIVERSAR",
"I WOULD YOU LIKE TO INVITE YOU ERIC  IN MY BROTHER WEDDING ANNIVERSARY "

`
]

console.log(invitation );




// ASSIGNMENT NO 15 


console.log(`${invitation} BUT  OUR FRIEND ERIC CANT JOIN IT`);

console.log(`NOW I'M INVITING MY NEW FRRIEND REPLACING ERIC`);

let invitationFinal = [
"I WANNA INVITE YOU  OWAIS IN MY BROTHER WEDDING ANNIVERSARY",
"I WOULD LIKE TO INVITE YOU YAZDAN IN MY BROTHER WEDDING ANNIVERSAR",
"I WOULD YOU LIKE TO INVITE YOU HENRY  IN MY BROTHER WEDDING ANNIVERSARY ON ERIC PLACE",

]
 
console.log(invitationFinal);

// CHAPTER NO 16


console.log(`NOW I HAVE A GREAT DINNER TABLE SO THAT I WANNA INVITE THREE MORE GUESTS`);

let bigTable = [`

"I WOULD YOU LIKE TO INVITE OWAIS ON MY BROTHER WEDDING ANNIVERSARY",
"I would like to invite HASEEB ON MY BROTHER WEDDING ANNIVERSARY",
"I WOULD LIKE TO INVITE ERIC ON MY BROTHER WEDDING AANNIVERARY",
"I WOULD LIKE TO INVITE MY FOURTH FRIEND ON MY BROTHER WEDDING ANNIVERSARY",
"I WOULD LIKE TO INVITE MY FIFTH FRIEND ON MY BROTHER WEDDING ANNIVERSARY",
"I WOULD LIKE TO INVITE MY SIXTHH FRIEND ON MY BROTHER WEDDING ANNIVERSARY"

`]

console.log(bigTable);


